/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedGroupGroupIdRouteImport } from './routes/_authenticated/group.$groupId'
import { Route as AuthenticatedGroupGroupIdResultRouteImport } from './routes/_authenticated/group.$groupId.result'
import { Route as AuthenticatedGroupGroupIdTierTierRouteImport } from './routes/_authenticated/group.$groupId.tier.$tier'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGroupGroupIdRoute =
  AuthenticatedGroupGroupIdRouteImport.update({
    id: '/group/$groupId',
    path: '/group/$groupId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupGroupIdResultRoute =
  AuthenticatedGroupGroupIdResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => AuthenticatedGroupGroupIdRoute,
  } as any)
const AuthenticatedGroupGroupIdTierTierRoute =
  AuthenticatedGroupGroupIdTierTierRouteImport.update({
    id: '/tier/$tier',
    path: '/tier/$tier',
    getParentRoute: () => AuthenticatedGroupGroupIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/group/$groupId': typeof AuthenticatedGroupGroupIdRouteWithChildren
  '/group/$groupId/result': typeof AuthenticatedGroupGroupIdResultRoute
  '/group/$groupId/tier/$tier': typeof AuthenticatedGroupGroupIdTierTierRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/group/$groupId': typeof AuthenticatedGroupGroupIdRouteWithChildren
  '/group/$groupId/result': typeof AuthenticatedGroupGroupIdResultRoute
  '/group/$groupId/tier/$tier': typeof AuthenticatedGroupGroupIdTierTierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/group/$groupId': typeof AuthenticatedGroupGroupIdRouteWithChildren
  '/_authenticated/group/$groupId/result': typeof AuthenticatedGroupGroupIdResultRoute
  '/_authenticated/group/$groupId/tier/$tier': typeof AuthenticatedGroupGroupIdTierTierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/profile'
    | '/group/$groupId'
    | '/group/$groupId/result'
    | '/group/$groupId/tier/$tier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/login'
    | '/profile'
    | '/'
    | '/group/$groupId'
    | '/group/$groupId/result'
    | '/group/$groupId/tier/$tier'
  id:
    | '__root__'
    | '/_authenticated'
    | '/admin'
    | '/login'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/group/$groupId'
    | '/_authenticated/group/$groupId/result'
    | '/_authenticated/group/$groupId/tier/$tier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/group/$groupId': {
      id: '/_authenticated/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupGroupIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/group/$groupId/result': {
      id: '/_authenticated/group/$groupId/result'
      path: '/result'
      fullPath: '/group/$groupId/result'
      preLoaderRoute: typeof AuthenticatedGroupGroupIdResultRouteImport
      parentRoute: typeof AuthenticatedGroupGroupIdRoute
    }
    '/_authenticated/group/$groupId/tier/$tier': {
      id: '/_authenticated/group/$groupId/tier/$tier'
      path: '/tier/$tier'
      fullPath: '/group/$groupId/tier/$tier'
      preLoaderRoute: typeof AuthenticatedGroupGroupIdTierTierRouteImport
      parentRoute: typeof AuthenticatedGroupGroupIdRoute
    }
  }
}

interface AuthenticatedGroupGroupIdRouteChildren {
  AuthenticatedGroupGroupIdResultRoute: typeof AuthenticatedGroupGroupIdResultRoute
  AuthenticatedGroupGroupIdTierTierRoute: typeof AuthenticatedGroupGroupIdTierTierRoute
}

const AuthenticatedGroupGroupIdRouteChildren: AuthenticatedGroupGroupIdRouteChildren =
  {
    AuthenticatedGroupGroupIdResultRoute: AuthenticatedGroupGroupIdResultRoute,
    AuthenticatedGroupGroupIdTierTierRoute:
      AuthenticatedGroupGroupIdTierTierRoute,
  }

const AuthenticatedGroupGroupIdRouteWithChildren =
  AuthenticatedGroupGroupIdRoute._addFileChildren(
    AuthenticatedGroupGroupIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGroupGroupIdRoute: typeof AuthenticatedGroupGroupIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGroupGroupIdRoute: AuthenticatedGroupGroupIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
