-- ============================================================
-- Car-Y-list: Complete database schema
-- Run this in Supabase SQL Editor
-- ============================================================

-- ── Enums ────────────────────────────────────────────────────

CREATE TYPE "UserRole" AS ENUM ('REGISTERED', 'ADMIN', 'PUBLIC');
CREATE TYPE "TaskPriority" AS ENUM ('NONE', 'LOW', 'MEDIUM', 'HIGH', 'URGENT');
CREATE TYPE "CollaborationRole" AS ENUM ('VIEWER', 'CONTRIBUTOR');
CREATE TYPE "VoteType" AS ENUM ('LIKE', 'DISLIKE');
CREATE TYPE "GroupRole" AS ENUM ('OWNER', 'MEMBER');
CREATE TYPE "Tier" AS ENUM ('S', 'A', 'B', 'C', 'D', 'E', 'F');

-- ── Core User table ───────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "User" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "clerkId" text UNIQUE,
  "fullName" text NOT NULL,
  "email" text NOT NULL UNIQUE,
  "passwordHash" text,
  "role" "UserRole" NOT NULL DEFAULT 'REGISTERED',
  "school" text,
  "studyMajor" text,
  "studyYear" text,
  "studyType" text,
  "avatarDataUrl" text,
  "deletedAt" timestamp with time zone,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "User_deletedAt_idx" ON "User" ("deletedAt");

-- ── StudyPlan (legacy, needed for FK references) ──────────────

CREATE TABLE IF NOT EXISTS "StudyPlan" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "userId" bigint NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "name" text NOT NULL,
  "description" text,
  "isActive" boolean NOT NULL DEFAULT true,
  "isShared" boolean NOT NULL DEFAULT false,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "StudyPlan_userId_idx" ON "StudyPlan" ("userId");
CREATE INDEX IF NOT EXISTS "StudyPlan_isActive_idx" ON "StudyPlan" ("isActive");
CREATE INDEX IF NOT EXISTS "StudyPlan_isShared_idx" ON "StudyPlan" ("isShared");

-- ── StudyPlanCollaborator ─────────────────────────────────────

CREATE TABLE IF NOT EXISTS "StudyPlanCollaborator" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "studyPlanId" bigint NOT NULL REFERENCES "StudyPlan"("id") ON DELETE CASCADE,
  "userId" bigint NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "role" "CollaborationRole" NOT NULL DEFAULT 'VIEWER',
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "StudyPlanCollaborator_studyPlanId_userId_unique" ON "StudyPlanCollaborator" ("studyPlanId", "userId");
CREATE INDEX IF NOT EXISTS "StudyPlanCollaborator_userId_idx" ON "StudyPlanCollaborator" ("userId");

-- ── Subject ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "Subject" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "userId" bigint NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "studyPlanId" bigint REFERENCES "StudyPlan"("id") ON DELETE SET NULL,
  "name" text NOT NULL,
  "teacher" text NOT NULL,
  "code" text NOT NULL,
  "isShared" boolean NOT NULL DEFAULT false,
  "isArchived" boolean NOT NULL DEFAULT false,
  "deletedAt" timestamp with time zone,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "Subject_userId_idx" ON "Subject" ("userId");
CREATE INDEX IF NOT EXISTS "Subject_studyPlanId_idx" ON "Subject" ("studyPlanId");
CREATE INDEX IF NOT EXISTS "Subject_isShared_idx" ON "Subject" ("isShared");
CREATE INDEX IF NOT EXISTS "Subject_deletedAt_idx" ON "Subject" ("deletedAt");
CREATE UNIQUE INDEX IF NOT EXISTS "Subject_userId_code_unique" ON "Subject" ("userId", "code");

-- ── Task ──────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "Task" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "userId" bigint NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "title" text NOT NULL,
  "done" boolean NOT NULL DEFAULT false,
  "priority" "TaskPriority" NOT NULL DEFAULT 'NONE',
  "deletedAt" timestamp with time zone,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "Task_userId_idx" ON "Task" ("userId");
CREATE INDEX IF NOT EXISTS "Task_deletedAt_idx" ON "Task" ("deletedAt");

-- ── FileRecord ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "FileRecord" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "userId" bigint NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "subjectId" bigint REFERENCES "Subject"("id") ON DELETE SET NULL,
  "fileKey" text UNIQUE,
  "fileUrl" text,
  "name" text NOT NULL,
  "size" integer NOT NULL,
  "addedLabel" text NOT NULL,
  "isShared" boolean NOT NULL DEFAULT false,
  "deletedAt" timestamp with time zone,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "FileRecord_userId_idx" ON "FileRecord" ("userId");
CREATE INDEX IF NOT EXISTS "FileRecord_subjectId_idx" ON "FileRecord" ("subjectId");
CREATE INDEX IF NOT EXISTS "FileRecord_isShared_idx" ON "FileRecord" ("isShared");
CREATE INDEX IF NOT EXISTS "FileRecord_deletedAt_idx" ON "FileRecord" ("deletedAt");

-- ── FileShare ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "FileShare" (
  "fileId" bigint NOT NULL,
  "userId" bigint NOT NULL,
  "permission" text NOT NULL DEFAULT 'read',
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY ("fileId", "userId")
);

CREATE INDEX IF NOT EXISTS "FileShare_fileId_idx" ON "FileShare" ("fileId");
CREATE INDEX IF NOT EXISTS "FileShare_userId_idx" ON "FileShare" ("userId");

-- ── FileRating ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "FileRating" (
  "fileId" bigint NOT NULL REFERENCES "FileRecord"("id") ON DELETE CASCADE,
  "userId" bigint NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "vote" "VoteType" NOT NULL,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY ("fileId", "userId")
);

CREATE INDEX IF NOT EXISTS "FileRating_fileId_idx" ON "FileRating" ("fileId");
CREATE INDEX IF NOT EXISTS "FileRating_userId_idx" ON "FileRating" ("userId");

-- ── Lesson ────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "Lesson" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "subjectId" bigint REFERENCES "Subject"("id") ON DELETE SET NULL,
  "userId" bigint REFERENCES "User"("id") ON DELETE SET NULL,
  "title" text NOT NULL,
  "content" text,
  "isShared" boolean NOT NULL DEFAULT false,
  "orderIndex" integer NOT NULL,
  "deletedAt" timestamp with time zone,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "Lesson_subjectId_idx" ON "Lesson" ("subjectId");
CREATE INDEX IF NOT EXISTS "Lesson_userId_idx" ON "Lesson" ("userId");
CREATE INDEX IF NOT EXISTS "Lesson_isShared_idx" ON "Lesson" ("isShared");
CREATE INDEX IF NOT EXISTS "Lesson_deletedAt_idx" ON "Lesson" ("deletedAt");

-- ── LessonRating ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "LessonRating" (
  "lessonId" bigint NOT NULL REFERENCES "Lesson"("id") ON DELETE CASCADE,
  "userId" bigint NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "vote" "VoteType" NOT NULL,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY ("lessonId", "userId")
);

CREATE INDEX IF NOT EXISTS "LessonRating_lessonId_idx" ON "LessonRating" ("lessonId");
CREATE INDEX IF NOT EXISTS "LessonRating_userId_idx" ON "LessonRating" ("userId");

-- ── Event ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "Event" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "userId" bigint NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "title" text NOT NULL,
  "date" date NOT NULL,
  "time" text,
  "location" text,
  "isShared" boolean NOT NULL DEFAULT false,
  "deletedAt" timestamp with time zone,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "Event_userId_idx" ON "Event" ("userId");
CREATE INDEX IF NOT EXISTS "Event_isShared_idx" ON "Event" ("isShared");
CREATE INDEX IF NOT EXISTS "Event_date_idx" ON "Event" ("date");
CREATE INDEX IF NOT EXISTS "Event_deletedAt_idx" ON "Event" ("deletedAt");

-- ── Tag ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "Tag" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "userId" bigint REFERENCES "User"("id") ON DELETE CASCADE,
  "name" text NOT NULL,
  "color" text NOT NULL DEFAULT 'blue',
  "isSystem" boolean NOT NULL DEFAULT false,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "Tag_userId_idx" ON "Tag" ("userId");
CREATE INDEX IF NOT EXISTS "Tag_isSystem_idx" ON "Tag" ("isSystem");

-- ── SubjectTag ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "SubjectTag" (
  "subjectId" bigint NOT NULL REFERENCES "Subject"("id") ON DELETE CASCADE,
  "tagId" bigint NOT NULL REFERENCES "Tag"("id") ON DELETE CASCADE,
  PRIMARY KEY ("subjectId", "tagId")
);

CREATE INDEX IF NOT EXISTS "SubjectTag_subjectId_idx" ON "SubjectTag" ("subjectId");
CREATE INDEX IF NOT EXISTS "SubjectTag_tagId_idx" ON "SubjectTag" ("tagId");

-- ============================================================
-- ── Car-Y-list: Tier List tables ─────────────────────────────
-- ============================================================

-- ── Group ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "Group" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "ownerId" bigint NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "Group_ownerId_idx" ON "Group" ("ownerId");

-- ── GroupMember ───────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "GroupMember" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "groupId" bigint NOT NULL REFERENCES "Group"("id") ON DELETE CASCADE,
  "userId" bigint NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "role" "GroupRole" NOT NULL DEFAULT 'MEMBER',
  "createdAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "GroupMember_groupId_userId_unique" ON "GroupMember" ("groupId", "userId");
CREATE INDEX IF NOT EXISTS "GroupMember_groupId_idx" ON "GroupMember" ("groupId");
CREATE INDEX IF NOT EXISTS "GroupMember_userId_idx" ON "GroupMember" ("userId");

-- ── Image ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "Image" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "groupId" bigint NOT NULL REFERENCES "Group"("id") ON DELETE CASCADE,
  "uploadedById" bigint NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "name" text NOT NULL,
  "fileKey" text,
  "fileUrl" text,
  "size" integer NOT NULL DEFAULT 0,
  "tier" "Tier",
  "ratedById" bigint REFERENCES "User"("id") ON DELETE SET NULL,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "Image_groupId_idx" ON "Image" ("groupId");
CREATE INDEX IF NOT EXISTS "Image_uploadedById_idx" ON "Image" ("uploadedById");
CREATE INDEX IF NOT EXISTS "Image_tier_idx" ON "Image" ("tier");

-- ── ImageRating ───────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "ImageRating" (
  "imageId" bigint NOT NULL REFERENCES "Image"("id") ON DELETE CASCADE,
  "userId" bigint NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "tier" "Tier" NOT NULL,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY ("imageId", "userId")
);

CREATE INDEX IF NOT EXISTS "ImageRating_imageId_idx" ON "ImageRating" ("imageId");
CREATE INDEX IF NOT EXISTS "ImageRating_userId_idx" ON "ImageRating" ("userId");

-- ── ImageComment ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "ImageComment" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "imageId" bigint NOT NULL REFERENCES "Image"("id") ON DELETE CASCADE,
  "userId" bigint NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "content" text NOT NULL,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "ImageComment_imageId_idx" ON "ImageComment" ("imageId");
CREATE INDEX IF NOT EXISTS "ImageComment_userId_idx" ON "ImageComment" ("userId");

-- ── Done! ─────────────────────────────────────────────────────
SELECT 'Schema created successfully!' as status;
