CREATE TYPE "public"."AnnotationTargetType" AS ENUM('LESSON', 'LESSON_NOTE', 'FILE_COMMENT');--> statement-breakpoint
CREATE TYPE "public"."CollaborationRole" AS ENUM('VIEWER', 'CONTRIBUTOR');--> statement-breakpoint
CREATE TYPE "public"."EventRecurrence" AS ENUM('NONE', 'DAILY', 'WEEKLY', 'MONTHLY');--> statement-breakpoint
CREATE TYPE "public"."TaskPriority" AS ENUM('NONE', 'LOW', 'MEDIUM', 'HIGH', 'URGENT');--> statement-breakpoint
CREATE TYPE "public"."UserRole" AS ENUM('REGISTERED', 'ADMIN');--> statement-breakpoint
CREATE TABLE "Event" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"userId" bigint NOT NULL,
	"subjectId" bigint,
	"title" text NOT NULL,
	"date" date NOT NULL,
	"time" text,
	"location" text,
	"isShared" boolean DEFAULT false NOT NULL,
	"recurrence" "EventRecurrence" DEFAULT 'NONE' NOT NULL,
	"recurrenceGroupId" text,
	"deletedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "FileComment" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "FileComment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"fileId" bigint NOT NULL,
	"userId" bigint NOT NULL,
	"comment" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "FileRecord" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "FileRecord_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"userId" bigint NOT NULL,
	"subjectId" bigint,
	"lessonId" bigint,
	"fileKey" text,
	"fileUrl" text,
	"name" text NOT NULL,
	"size" integer NOT NULL,
	"addedLabel" text NOT NULL,
	"isShared" boolean DEFAULT false NOT NULL,
	"deletedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "FileRecord_fileKey_unique" UNIQUE("fileKey")
);
--> statement-breakpoint
CREATE TABLE "LessonNote" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "LessonNote_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"lessonId" bigint NOT NULL,
	"userId" bigint NOT NULL,
	"note" text NOT NULL,
	"isPinned" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Lesson" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Lesson_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"subjectId" bigint,
	"studyPlanId" bigint,
	"title" text NOT NULL,
	"content" text,
	"isShared" boolean DEFAULT false NOT NULL,
	"orderIndex" integer NOT NULL,
	"deletedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "StudyPlanCollaborator" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "StudyPlanCollaborator_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"studyPlanId" bigint NOT NULL,
	"userId" bigint NOT NULL,
	"role" "CollaborationRole" DEFAULT 'VIEWER' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "StudyPlan" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "StudyPlan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"userId" bigint NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"faculty" text,
	"startDate" date,
	"endDate" date,
	"isActive" boolean DEFAULT true NOT NULL,
	"isShared" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Subject" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Subject_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"userId" bigint NOT NULL,
	"studyPlanId" bigint,
	"name" text NOT NULL,
	"teacher" text NOT NULL,
	"code" text NOT NULL,
	"isShared" boolean DEFAULT false NOT NULL,
	"deletedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Task" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"userId" bigint NOT NULL,
	"subjectId" bigint,
	"studyPlanId" bigint,
	"title" text NOT NULL,
	"done" boolean DEFAULT false NOT NULL,
	"favorite" boolean DEFAULT false NOT NULL,
	"tag" text,
	"deadline" timestamp with time zone,
	"deletedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "TextAnnotation" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "TextAnnotation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"targetType" "AnnotationTargetType" NOT NULL,
	"targetId" bigint NOT NULL,
	"userId" bigint NOT NULL,
	"startOffset" integer NOT NULL,
	"endOffset" integer NOT NULL,
	"selectedText" text NOT NULL,
	"comment" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "User" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "User_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"clerkId" text,
	"fullName" text NOT NULL,
	"email" text NOT NULL,
	"passwordHash" text,
	"role" "UserRole" DEFAULT 'REGISTERED' NOT NULL,
	"school" text,
	"faculty" text,
	"studyMajor" text,
	"studyYear" text,
	"studyType" text,
	"birthDate" date,
	"bio" text,
	"avatarDataUrl" text,
	"contactEmail" text,
	"deletedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "User_clerkId_unique" UNIQUE("clerkId"),
	CONSTRAINT "User_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "Event" ADD CONSTRAINT "Event_userId_User_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Event" ADD CONSTRAINT "Event_subjectId_Subject_id_fk" FOREIGN KEY ("subjectId") REFERENCES "public"."Subject"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "FileComment" ADD CONSTRAINT "FileComment_fileId_FileRecord_id_fk" FOREIGN KEY ("fileId") REFERENCES "public"."FileRecord"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "FileComment" ADD CONSTRAINT "FileComment_userId_User_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "FileRecord" ADD CONSTRAINT "FileRecord_userId_User_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "FileRecord" ADD CONSTRAINT "FileRecord_subjectId_Subject_id_fk" FOREIGN KEY ("subjectId") REFERENCES "public"."Subject"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "FileRecord" ADD CONSTRAINT "FileRecord_lessonId_Lesson_id_fk" FOREIGN KEY ("lessonId") REFERENCES "public"."Lesson"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "LessonNote" ADD CONSTRAINT "LessonNote_lessonId_Lesson_id_fk" FOREIGN KEY ("lessonId") REFERENCES "public"."Lesson"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "LessonNote" ADD CONSTRAINT "LessonNote_userId_User_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Lesson" ADD CONSTRAINT "Lesson_subjectId_Subject_id_fk" FOREIGN KEY ("subjectId") REFERENCES "public"."Subject"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Lesson" ADD CONSTRAINT "Lesson_studyPlanId_StudyPlan_id_fk" FOREIGN KEY ("studyPlanId") REFERENCES "public"."StudyPlan"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "StudyPlanCollaborator" ADD CONSTRAINT "StudyPlanCollaborator_studyPlanId_StudyPlan_id_fk" FOREIGN KEY ("studyPlanId") REFERENCES "public"."StudyPlan"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "StudyPlanCollaborator" ADD CONSTRAINT "StudyPlanCollaborator_userId_User_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "StudyPlan" ADD CONSTRAINT "StudyPlan_userId_User_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Subject" ADD CONSTRAINT "Subject_userId_User_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Subject" ADD CONSTRAINT "Subject_studyPlanId_StudyPlan_id_fk" FOREIGN KEY ("studyPlanId") REFERENCES "public"."StudyPlan"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Task" ADD CONSTRAINT "Task_userId_User_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Task" ADD CONSTRAINT "Task_subjectId_Subject_id_fk" FOREIGN KEY ("subjectId") REFERENCES "public"."Subject"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Task" ADD CONSTRAINT "Task_studyPlanId_StudyPlan_id_fk" FOREIGN KEY ("studyPlanId") REFERENCES "public"."StudyPlan"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TextAnnotation" ADD CONSTRAINT "TextAnnotation_userId_User_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "Event_userId_idx" ON "Event" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "Event_subjectId_idx" ON "Event" USING btree ("subjectId");--> statement-breakpoint
CREATE INDEX "Event_isShared_idx" ON "Event" USING btree ("isShared");--> statement-breakpoint
CREATE INDEX "Event_date_idx" ON "Event" USING btree ("date");--> statement-breakpoint
CREATE INDEX "Event_deletedAt_idx" ON "Event" USING btree ("deletedAt");--> statement-breakpoint
CREATE INDEX "Event_recurrenceGroupId_idx" ON "Event" USING btree ("recurrenceGroupId");--> statement-breakpoint
CREATE INDEX "FileComment_fileId_idx" ON "FileComment" USING btree ("fileId");--> statement-breakpoint
CREATE INDEX "FileComment_userId_idx" ON "FileComment" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "FileRecord_userId_idx" ON "FileRecord" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "FileRecord_subjectId_idx" ON "FileRecord" USING btree ("subjectId");--> statement-breakpoint
CREATE INDEX "FileRecord_lessonId_idx" ON "FileRecord" USING btree ("lessonId");--> statement-breakpoint
CREATE INDEX "FileRecord_isShared_idx" ON "FileRecord" USING btree ("isShared");--> statement-breakpoint
CREATE INDEX "FileRecord_deletedAt_idx" ON "FileRecord" USING btree ("deletedAt");--> statement-breakpoint
CREATE INDEX "LessonNote_lessonId_idx" ON "LessonNote" USING btree ("lessonId");--> statement-breakpoint
CREATE INDEX "LessonNote_userId_idx" ON "LessonNote" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "Lesson_subjectId_idx" ON "Lesson" USING btree ("subjectId");--> statement-breakpoint
CREATE INDEX "Lesson_studyPlanId_idx" ON "Lesson" USING btree ("studyPlanId");--> statement-breakpoint
CREATE INDEX "Lesson_isShared_idx" ON "Lesson" USING btree ("isShared");--> statement-breakpoint
CREATE INDEX "Lesson_deletedAt_idx" ON "Lesson" USING btree ("deletedAt");--> statement-breakpoint
CREATE UNIQUE INDEX "StudyPlanCollaborator_studyPlanId_userId_unique" ON "StudyPlanCollaborator" USING btree ("studyPlanId","userId");--> statement-breakpoint
CREATE INDEX "StudyPlanCollaborator_userId_idx" ON "StudyPlanCollaborator" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "StudyPlan_userId_idx" ON "StudyPlan" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "StudyPlan_isActive_idx" ON "StudyPlan" USING btree ("isActive");--> statement-breakpoint
CREATE INDEX "StudyPlan_isShared_idx" ON "StudyPlan" USING btree ("isShared");--> statement-breakpoint
CREATE INDEX "Subject_userId_idx" ON "Subject" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "Subject_studyPlanId_idx" ON "Subject" USING btree ("studyPlanId");--> statement-breakpoint
CREATE INDEX "Subject_isShared_idx" ON "Subject" USING btree ("isShared");--> statement-breakpoint
CREATE INDEX "Subject_deletedAt_idx" ON "Subject" USING btree ("deletedAt");--> statement-breakpoint
CREATE UNIQUE INDEX "Subject_userId_code_unique" ON "Subject" USING btree ("userId","code");--> statement-breakpoint
CREATE INDEX "Task_userId_idx" ON "Task" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "Task_subjectId_idx" ON "Task" USING btree ("subjectId");--> statement-breakpoint
CREATE INDEX "Task_studyPlanId_idx" ON "Task" USING btree ("studyPlanId");--> statement-breakpoint
CREATE INDEX "Task_deadline_idx" ON "Task" USING btree ("deadline");--> statement-breakpoint
CREATE INDEX "Task_deletedAt_idx" ON "Task" USING btree ("deletedAt");--> statement-breakpoint
CREATE INDEX "TextAnnotation_targetType_targetId_idx" ON "TextAnnotation" USING btree ("targetType","targetId");--> statement-breakpoint
CREATE INDEX "TextAnnotation_userId_idx" ON "TextAnnotation" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "User_deletedAt_idx" ON "User" USING btree ("deletedAt");