CREATE TABLE "SubjectTag" (
	"subjectId" bigint NOT NULL,
	"tagId" bigint NOT NULL,
	CONSTRAINT "SubjectTag_subjectId_tagId_pk" PRIMARY KEY("subjectId","tagId")
);
--> statement-breakpoint
CREATE TABLE "Tag" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"userId" bigint,
	"name" text NOT NULL,
	"color" text DEFAULT 'blue' NOT NULL,
	"isSystem" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "SubjectTag" ADD CONSTRAINT "SubjectTag_subjectId_Subject_id_fk" FOREIGN KEY ("subjectId") REFERENCES "public"."Subject"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "SubjectTag" ADD CONSTRAINT "SubjectTag_tagId_Tag_id_fk" FOREIGN KEY ("tagId") REFERENCES "public"."Tag"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Tag" ADD CONSTRAINT "Tag_userId_User_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "SubjectTag_subjectId_idx" ON "SubjectTag" USING btree ("subjectId");--> statement-breakpoint
CREATE INDEX "SubjectTag_tagId_idx" ON "SubjectTag" USING btree ("tagId");--> statement-breakpoint
CREATE INDEX "Tag_userId_idx" ON "Tag" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "Tag_isSystem_idx" ON "Tag" USING btree ("isSystem");