CREATE TABLE "SubjectShare" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "SubjectShare_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"subjectId" bigint NOT NULL,
	"userId" bigint NOT NULL,
	"isArchived" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "SubjectShare" ADD CONSTRAINT "SubjectShare_subjectId_Subject_id_fk" FOREIGN KEY ("subjectId") REFERENCES "public"."Subject"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "SubjectShare" ADD CONSTRAINT "SubjectShare_userId_User_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "SubjectShare_subjectId_userId_unique" ON "SubjectShare" USING btree ("subjectId","userId");--> statement-breakpoint
CREATE INDEX "SubjectShare_userId_idx" ON "SubjectShare" USING btree ("userId");