CREATE TYPE "public"."GroupRole" AS ENUM('OWNER', 'MEMBER');--> statement-breakpoint
CREATE TYPE "public"."Tier" AS ENUM('S', 'A', 'B', 'C', 'D', 'E', 'F');--> statement-breakpoint
CREATE TABLE "GroupMember" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "GroupMember_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"groupId" bigint NOT NULL,
	"userId" bigint NOT NULL,
	"role" "GroupRole" DEFAULT 'MEMBER' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Group" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"ownerId" bigint NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Image" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"groupId" bigint NOT NULL,
	"uploadedById" bigint NOT NULL,
	"name" text NOT NULL,
	"fileKey" text,
	"fileUrl" text,
	"size" integer DEFAULT 0 NOT NULL,
	"tier" "Tier",
	"ratedById" bigint,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "GroupMember" ADD CONSTRAINT "GroupMember_groupId_Group_id_fk" FOREIGN KEY ("groupId") REFERENCES "public"."Group"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "GroupMember" ADD CONSTRAINT "GroupMember_userId_User_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Group" ADD CONSTRAINT "Group_ownerId_User_id_fk" FOREIGN KEY ("ownerId") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Image" ADD CONSTRAINT "Image_groupId_Group_id_fk" FOREIGN KEY ("groupId") REFERENCES "public"."Group"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Image" ADD CONSTRAINT "Image_uploadedById_User_id_fk" FOREIGN KEY ("uploadedById") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Image" ADD CONSTRAINT "Image_ratedById_User_id_fk" FOREIGN KEY ("ratedById") REFERENCES "public"."User"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "GroupMember_groupId_userId_unique" ON "GroupMember" USING btree ("groupId","userId");--> statement-breakpoint
CREATE INDEX "GroupMember_groupId_idx" ON "GroupMember" USING btree ("groupId");--> statement-breakpoint
CREATE INDEX "GroupMember_userId_idx" ON "GroupMember" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "Group_ownerId_idx" ON "Group" USING btree ("ownerId");--> statement-breakpoint
CREATE INDEX "Image_groupId_idx" ON "Image" USING btree ("groupId");--> statement-breakpoint
CREATE INDEX "Image_uploadedById_idx" ON "Image" USING btree ("uploadedById");--> statement-breakpoint
CREATE INDEX "Image_tier_idx" ON "Image" USING btree ("tier");