CREATE TABLE "ImageComment" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ImageComment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"imageId" bigint NOT NULL,
	"userId" bigint NOT NULL,
	"content" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ImageRating" (
	"imageId" bigint NOT NULL,
	"userId" bigint NOT NULL,
	"tier" "Tier" NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ImageRating_imageId_userId_pk" PRIMARY KEY("imageId","userId")
);
--> statement-breakpoint
ALTER TABLE "ImageComment" ADD CONSTRAINT "ImageComment_imageId_Image_id_fk" FOREIGN KEY ("imageId") REFERENCES "public"."Image"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ImageComment" ADD CONSTRAINT "ImageComment_userId_User_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ImageRating" ADD CONSTRAINT "ImageRating_imageId_Image_id_fk" FOREIGN KEY ("imageId") REFERENCES "public"."Image"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ImageRating" ADD CONSTRAINT "ImageRating_userId_User_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ImageComment_imageId_idx" ON "ImageComment" USING btree ("imageId");--> statement-breakpoint
CREATE INDEX "ImageComment_userId_idx" ON "ImageComment" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "ImageRating_imageId_idx" ON "ImageRating" USING btree ("imageId");--> statement-breakpoint
CREATE INDEX "ImageRating_userId_idx" ON "ImageRating" USING btree ("userId");